### ISSUE TITLE
Anti-virus flag

### ISSUE THREAD

**Issue by ArtByChance** [shells-dw/StreamDeck-OSC#6]
AVG flags this as IDP.Generic.

False Positive due to the nature of the plugin?

**Comment by shells-dw** [comment]
This is a question that would need to be addressed to your snake oil, I mean AntiVirus, manufacturer.

It is out of my control, what and how any of the hundreds of AV software out there detects anything and why.

IDP.Generic is often used as a general heuristic detection result, heuristic here meaning your AV software "thinks" by itself this might be something that would/could steal personal or identity data, which is what IDP stands for - identity protection.

The code of the plugin does nothing alike, you can see all the code here, if you don't trust the prepackaged and compiled result, feel free to compile and package it yourself after analyzing the code.

I am certain, being the author of the plugin, that this is a false positive.
But since there's no reason to trust my words any more than the result of your AV, generally it's always a good idea to upload questionable files (that do not contain personal data or are secretive or IP protected), executables and anything you're not sure if it's clean to [virustotal.com ](https://www.virustotal.com)where it gets analyzed on their systems without any danger to yours against 90 different AV products more or less in real time.
There, the current release is flagged as suspicious once (which is more or less normal for any executable you upload there, any overly careful niche-AV will flag it as suspicious or something.generic or alike) while 89 scanners don't detect anything.

Hope that helps clearing up any confusion.

Cheers

**Comment by ArtByChance** [comment]
I assumed so, just being overly cautious. 
Sent false positive form to AVG and they just confirmed and corrected.
Thanks!
